require("nutty.remap")
require('nutty.indent-blankline')
require('nutty.lualine')
require('nutty.nvim-tree')
require('nutty.telescope')
require('nutty.lsp')
require('nutty.nvim-treesitter')
require('nutty.git')
require('nutty.todo-comments')
require('nutty.rust')
require("nutty.theme")
require("nutty.copilot")

-- Plugins we just want to init
require('Comment').setup()
