name: "Build System"
on:
  pull_request:
  push:

jobs:
  build-systems:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        version: ["G14-nixos"]
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: git diff --quiet && exit 0 || true
      - run: nix-env --quiet -j8 -iA cachix -f https://cachix.org/api/v1/install
      - run: cachix --version
      - run: cachix authtoken ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build -L --no-link .#nixosConfigurations.${{matrix.version}}.config.system.build.toplevel
      - run: nix eval --json .#nixosConfigurations.${{matrix.version}}.config.system.build.toplevel | sed 's/"\(.*\)"/\1/' | cachix push nuttyshrimp
