name: "Build System"
on:
  pull_request:
  push:

jobs:
  build-systems:
    runs-on: self-hosted
    strategy:
      matrix:
        version: ["G14-nixos"]
    steps:
      - uses: actions/checkout@v4
      - run: git diff --quiet && exit 0 || true
      - run: nix-env --quiet -j8 -iA cachix -f https://cachix.org/api/v1/install
      - run: cachix --version
      - run: cachix authtoken ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: cachix use nuttyshrimp
      - run: cachix use hyprland
      - run: cachix use nix-community
      - run: echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
      - run: nix-prefetch-url --name displaylink-580.zip "https://www.synaptics.com/sites/default/files/exe_files/2023-08/DisplayLink%20USB%20Graphics%20Software%20for%20Ubuntu5.8-EXE.zip"
      - run: nix build -L --no-link .#nixosConfigurations.${{matrix.version}}.config.system.build.toplevel
      - run: nix-store --verify --repair --check-contents
      - run: echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
      - run: nix eval --json .#nixosConfigurations.${{matrix.version}}.config.system.build.toplevel | sed 's/"\(.*\)"/\1/' | cachix push nuttyshrimp -c 12
