name: "Update systems"
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 4 * * *'

jobs:
  update-lock-file:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix flake update
      - name: Upload lock file
        uses: actions/upload-artifact@v4
        with:
          name: flake-lock
          path: flake.lock

  build-systems:
    runs-on: self-hosted
    needs: update-lock-file
    strategy:
      matrix:
        version: ["G14-nixos"]
    steps:
      - uses: actions/checkout@v4
      - name: Download lock file
        uses: actions/download-artifact@v4
        with:
          name: flake-lock
      - run: git diff --quiet && exit 0 || true
      - run: nix-env --quiet -j8 -iA cachix -f https://cachix.org/api/v1/install
      - run: cachix --version
      - run: cachix authtoken ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
      - run: nix-prefetch-url --name displaylink-580.zip "https://www.synaptics.com/sites/default/files/exe_files/2023-08/DisplayLink%20USB%20Graphics%20Software%20for%20Ubuntu5.8-EXE.zip"
      - run: cachix use nuttyshrimp
      - run: cachix use hyprland
      - run: cachix use nix-community
      - run: nix build -L --no-link .#nixosConfigurations.${{matrix.version}}.config.system.build.toplevel
      - run: nix-store --verify --repair --check-contents
      - run: echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
      - run: nix eval --json .#nixosConfigurations.${{matrix.version}}.config.system.build.toplevel | sed 's/"\(.*\)"/\1/' | cachix push nuttyshrimp -c 12

  commit-lock-file:
    runs-on: ubuntu-22.04
    needs: build-systems
    steps:
      - uses: actions/checkout@v4
      - name: Download lock file
        uses: actions/download-artifact@v4
        with:
          name: flake-lock
            
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: Update dependencies

